#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = require_once __DIR__.'/bootstrap/app.php';

if ($status instanceof \Illuminate\Contracts\Console\Kernel) {
    $status = $status->handle(
        $input = new \Symfony\Component\Console\Input\ArgvInput,
        new \Symfony\Component\Console\Output\ConsoleOutput
    );
} elseif ($status instanceof \Illuminate\Foundation\Application) {
    $status = $status->handleCommand(
        new \Symfony\Component\Console\Input\ArgvInput
    );
}

exit($status);
